name: dartz
description: Dart Monad IO Runtime
version: 0.0.1
repository: https://github.com/mobilemindtec/dartz.dart

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
